import { uniformSeasonalityWeights } from "@/lib/seasonality";
import { BaselineInput, Task } from "@/lib/types";

const INITIATIVE_DEFAULTS: Pick<
  Task,
  "initiativeStatus" | "description" | "problemStatement" | "confidence" | "effort" | "impactCategory"
> = {
  initiativeStatus: "planned",
  description: "",
  problemStatement: "",
  confidence: "medium",
  effort: "m",
  impactCategory: "conversion",
};

export const DEFAULT_BASELINE: BaselineInput = {
  sessions: 32191999,
  catalogCr: 0.61,
  pdpCr: 0.735,
  atcCr: 0.27,
  checkoutCr: 0.44,
  orderCr: 0.49,
  buyoutRate: 0.62,
  atv: 2312.912,
  upt: 2.536,
  seasonalityWeights: uniformSeasonalityWeights(),
};

type TaskSeed = Partial<Omit<Task, "id">> &
  Pick<Task, "project" | "taskName" | "priority" | "releaseMonth" | "active" | "comment">;

const createTask = (task: TaskSeed, id: number): Task => {
  const merged: Task = {
    id: `task-${id}`,
    ...INITIATIVE_DEFAULTS,
    stage1: "order",
    impact1Type: "relative_percent",
    impact1Value: 0,
    impact2Value: 0,
    ...task,
    releaseMonth: task.releaseMonth,
    devCommittedReleaseMonth: task.devCommittedReleaseMonth ?? task.releaseMonth,
  };
  return merged;
};

export const DEFAULT_TASKS: Task[] = [
  createTask(
    {
      project: "New Checkout",
      taskName: "Checkout Redesign",
      priority: "p1",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.15,
      stage2: "checkout",
      impact2Type: "relative_percent",
      impact2Value: 0.04,
      releaseMonth: 4,
      active: true,
      comment: "Черновая гипотеза из ТЗ: снять фрикцию в чекауте и усилить order CR.",
    },
    1,
  ),
  createTask(
    {
      project: "New Checkout",
      taskName: "Delivery time slot selection",
      priority: "p2",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 4,
      active: true,
      comment: "Дата из PDF. Значение можно заменить на расчет продакта.",
    },
    2,
  ),
  createTask(
    {
      project: "New Checkout",
      taskName: "Integration with PDP Delivery",
      priority: "p2",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 4,
      active: true,
      comment: "Синхронизирует обещание доставки между PDP и checkout.",
    },
    3,
  ),
  createTask(
    {
      project: "New Checkout",
      taskName: "Integration with Yandex Delivery",
      priority: "p2",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 4,
      active: true,
      comment: "Предзаполнено по PDF, значение можно откорректировать.",
    },
    4,
  ),
  createTask(
    {
      project: "New Checkout",
      taskName: "BNPL",
      priority: "p1",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.03,
      stage2: "atv",
      impact2Type: "relative_percent",
      impact2Value: 0.05,
      releaseMonth: 4,
      active: true,
      comment: "Часто влияет и на completion, и на средний чек.",
    },
    5,
  ),
  createTask(
    {
      project: "New Checkout",
      taskName: "Partial Order Fulfillment",
      priority: "p1",
      stage1: "buyout",
      impact1Type: "relative_percent",
      impact1Value: 0.04,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 7,
      active: true,
      comment: "Повышает выкуп и net revenue.",
    },
    6,
  ),
  createTask(
    {
      project: "New Cart",
      taskName: "Cart checkboxes / selection of items in the cart",
      priority: "p1",
      stage1: "checkout",
      impact1Type: "relative_percent",
      impact1Value: 0.04,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 3,
      active: true,
      comment: "По PDF задача относится к Cart -> Checkout CR.",
    },
    7,
  ),
  createTask(
    {
      project: "PDP",
      taskName: "PDP delivery info block",
      priority: "p2",
      stage1: "atc",
      impact1Type: "relative_percent",
      impact1Value: 0.025,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 4,
      active: true,
      comment: "Коммерческий блок с доставкой и возвратом на PDP.",
    },
    8,
  ),
  createTask(
    {
      project: "Recs and perso",
      taskName: "Relevant Recommendation in Cart",
      priority: "p2",
      stage1: "atv",
      impact1Type: "relative_percent",
      impact1Value: 0.03,
      stage2: "upt",
      impact2Type: "relative_percent",
      impact2Value: 0.03,
      releaseMonth: 4,
      active: true,
      comment: "Рекомендации в корзине обычно растят UPT и чек.",
    },
    9,
  ),
  createTask(
    {
      project: "Cart Split",
      taskName: "Cart Split",
      priority: "p1",
      stage1: "checkout",
      impact1Type: "absolute_pp",
      impact1Value: 0.02,
      stage2: "atv",
      impact2Type: "relative_percent",
      impact2Value: 0.05,
      releaseMonth: 6,
      active: true,
      comment: "Пример из ТЗ: +2 pp к checkout CR и +5% к ATV.",
    },
    10,
  ),
  createTask(
    {
      project: "UX|UI",
      taskName: "New Homepage",
      priority: "p2",
      stage1: "catalog",
      impact1Type: "relative_percent",
      impact1Value: 0.01,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 7,
      active: true,
      comment: "Можно использовать как рост попаданий в каталог.",
    },
    11,
  ),
  createTask(
    {
      project: "UX|UI",
      taskName: "New Navigation Menu",
      priority: "p2",
      stage1: "catalog",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 8,
      active: true,
      comment: "Черновой uplift для перехода в каталог.",
    },
    12,
  ),
  createTask(
    {
      project: "UX|UI",
      taskName: "New Product Listing",
      priority: "p1",
      stage1: "pdp",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: "atc",
      impact2Type: "relative_percent",
      impact2Value: 0.02,
      releaseMonth: 9,
      active: true,
      comment: "Листинг влияет на переходы в PDP и качество трафика в корзину.",
    },
    13,
  ),
  createTask(
    {
      project: "Promo",
      taskName: "Promotion Landing Page Builder",
      priority: "p2",
      stage1: "catalog",
      impact1Type: "relative_percent",
      impact1Value: 0.015,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 9,
      active: true,
      comment: "Условный uplift для посадочных под промо.",
    },
    14,
  ),
  createTask(
    {
      project: "Organic traffic",
      taskName: "SEO & Organic Traffic Recovery",
      priority: "p1",
      stage1: "traffic",
      impact1Type: "relative_percent",
      impact1Value: 0.06,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 7,
      active: true,
      comment: "Задача на трафик из PDF.",
    },
    15,
  ),
  createTask(
    {
      project: "Promo",
      taskName: "Cascading Promo Codes",
      priority: "p3",
      stage1: "buyout",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: "order",
      impact2Type: "relative_percent",
      impact2Value: 0.01,
      releaseMonth: 11,
      active: true,
      comment: "Можно быстро перекинуть на retention/order по вашему сценарию.",
    },
    16,
  ),
  createTask(
    {
      project: "Fast front A/B",
      taskName: "A/B Testing Platform",
      priority: "p3",
      stage1: "atc",
      impact1Type: "relative_percent",
      impact1Value: 0.01,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 10,
      active: true,
      comment: "Служебная задача, если хотите учитывать как отдельный uplift.",
    },
    17,
  ),
  createTask(
    {
      project: "Recs and perso",
      taskName: "Gravity Field",
      priority: "p2",
      stage1: "atc",
      impact1Type: "relative_percent",
      impact1Value: 0.015,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 11,
      active: true,
      comment: "Персонализация, предзаполнена как uplift ATC CR.",
    },
    18,
  ),
  createTask(
    {
      project: "Tech debt",
      taskName: "Load speed",
      priority: "p2",
      stage1: "pdp",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: "atc",
      impact2Type: "relative_percent",
      impact2Value: 0.01,
      releaseMonth: 12,
      active: true,
      comment: "Load speed обычно улучшает глубину и последующие CR.",
    },
    19,
  ),
];
