import { BaselineInput, ImpactType, Task, TrafficScenarioKey } from "@/lib/types";

export const MONTH_LABELS = [
  "Янв",
  "Фев",
  "Мар",
  "Апр",
  "Май",
  "Июн",
  "Июл",
  "Авг",
  "Сен",
  "Окт",
  "Ноя",
  "Дек",
] as const;

export const STAGE_LABELS = {
  catalog: "Каталог",
  pdp: "Карточка товара",
  atc: "Добавление в корзину",
  checkout: "Чекаут",
  order: "Заказ",
  traffic: "Трафик",
  atv: "ATV / средний чек",
  buyout: "% выкупа",
  upt: "UPT",
} as const;

export const IMPACT_TYPE_LABELS: Record<ImpactType, string> = {
  relative_percent: "% рост / снижение",
  absolute_pp: "П.п.",
  absolute_value: "Абсолютное значение",
};

export const TRAFFIC_SCENARIOS: Record<
  TrafficScenarioKey,
  { label: string; multiplier: number }
> = {
  base: { label: "Base 100%", multiplier: 1 },
  plus15: { label: "Traffic +15%", multiplier: 1.15 },
  plus20: { label: "Traffic +20%", multiplier: 1.2 },
  plus30: { label: "Traffic +30%", multiplier: 1.3 },
};

export const DEFAULT_BASELINE: BaselineInput = {
  sessions: 32191999,
  catalog: 20469722,
  pdp: 13975634,
  atc: 3513201,
  checkout: 1545252,
  orders: 642534,
  buyoutRate: 0.62,
  atv: 2312.912,
  upt: 2.536,
};

const createTask = (task: Omit<Task, "id">, id: number): Task => ({
  id: `task-${id}`,
  ...task,
});

export const DEFAULT_TASKS: Task[] = [
  createTask(
    {
      stream: "New Checkout",
      taskName: "Checkout Redesign",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.15,
      stage2: "checkout",
      impact2Type: "relative_percent",
      impact2Value: 0.04,
      releaseMonth: 4,
      active: true,
      comment: "Черновая гипотеза из ТЗ: снять фрикцию в чекауте и усилить order CR.",
    },
    1,
  ),
  createTask(
    {
      stream: "New Checkout",
      taskName: "Delivery time slot selection",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 4,
      active: true,
      comment: "Дата из PDF. Значение можно заменить на расчет продакта.",
    },
    2,
  ),
  createTask(
    {
      stream: "New Checkout",
      taskName: "Integration with PDP Delivery",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 4,
      active: true,
      comment: "Синхронизирует обещание доставки между PDP и checkout.",
    },
    3,
  ),
  createTask(
    {
      stream: "New Checkout",
      taskName: "Integration with Yandex Delivery",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 4,
      active: true,
      comment: "Предзаполнено по PDF, значение можно откорректировать.",
    },
    4,
  ),
  createTask(
    {
      stream: "New Checkout",
      taskName: "BNPL",
      stage1: "order",
      impact1Type: "relative_percent",
      impact1Value: 0.03,
      stage2: "atv",
      impact2Type: "relative_percent",
      impact2Value: 0.05,
      releaseMonth: 4,
      active: true,
      comment: "Часто влияет и на completion, и на средний чек.",
    },
    5,
  ),
  createTask(
    {
      stream: "New Checkout",
      taskName: "Partial Order Fulfillment",
      stage1: "buyout",
      impact1Type: "relative_percent",
      impact1Value: 0.04,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 7,
      active: true,
      comment: "Повышает выкуп и net revenue.",
    },
    6,
  ),
  createTask(
    {
      stream: "New Cart",
      taskName: "Cart checkboxes / selection of items in the cart",
      stage1: "checkout",
      impact1Type: "relative_percent",
      impact1Value: 0.04,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 3,
      active: true,
      comment: "По PDF задача относится к Cart -> Checkout CR.",
    },
    7,
  ),
  createTask(
    {
      stream: "PDP",
      taskName: "PDP delivery info block",
      stage1: "atc",
      impact1Type: "relative_percent",
      impact1Value: 0.025,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 4,
      active: true,
      comment: "Коммерческий блок с доставкой и возвратом на PDP.",
    },
    8,
  ),
  createTask(
    {
      stream: "Recs and perso",
      taskName: "Relevant Recommendation in Cart",
      stage1: "atv",
      impact1Type: "relative_percent",
      impact1Value: 0.03,
      stage2: "upt",
      impact2Type: "relative_percent",
      impact2Value: 0.03,
      releaseMonth: 4,
      active: true,
      comment: "Рекомендации в корзине обычно растят UPT и чек.",
    },
    9,
  ),
  createTask(
    {
      stream: "Cart Split",
      taskName: "Cart Split",
      stage1: "checkout",
      impact1Type: "absolute_pp",
      impact1Value: 0.02,
      stage2: "atv",
      impact2Type: "relative_percent",
      impact2Value: 0.05,
      releaseMonth: 6,
      active: true,
      comment: "Пример из ТЗ: +2 pp к checkout CR и +5% к ATV.",
    },
    10,
  ),
  createTask(
    {
      stream: "UX|UI",
      taskName: "New Homepage",
      stage1: "catalog",
      impact1Type: "relative_percent",
      impact1Value: 0.01,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 7,
      active: true,
      comment: "Можно использовать как рост попаданий в каталог.",
    },
    11,
  ),
  createTask(
    {
      stream: "UX|UI",
      taskName: "New Navigation Menu",
      stage1: "catalog",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 8,
      active: true,
      comment: "Черновой uplift для перехода в каталог.",
    },
    12,
  ),
  createTask(
    {
      stream: "UX|UI",
      taskName: "New Product Listing",
      stage1: "pdp",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: "atc",
      impact2Type: "relative_percent",
      impact2Value: 0.02,
      releaseMonth: 9,
      active: true,
      comment: "Листинг влияет на переходы в PDP и качество трафика в корзину.",
    },
    13,
  ),
  createTask(
    {
      stream: "Promo",
      taskName: "Promotion Landing Page Builder",
      stage1: "catalog",
      impact1Type: "relative_percent",
      impact1Value: 0.015,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 9,
      active: true,
      comment: "Условный uplift для посадочных под промо.",
    },
    14,
  ),
  createTask(
    {
      stream: "Organic traffic",
      taskName: "SEO & Organic Traffic Recovery",
      stage1: "traffic",
      impact1Type: "relative_percent",
      impact1Value: 0.06,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 7,
      active: true,
      comment: "Задача на трафик из PDF.",
    },
    15,
  ),
  createTask(
    {
      stream: "Promo",
      taskName: "Cascading Promo Codes",
      stage1: "buyout",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: "order",
      impact2Type: "relative_percent",
      impact2Value: 0.01,
      releaseMonth: 11,
      active: true,
      comment: "Можно быстро перекинуть на retention/order по вашему сценарию.",
    },
    16,
  ),
  createTask(
    {
      stream: "Fast front A/B",
      taskName: "A/B Testing Platform",
      stage1: "atc",
      impact1Type: "relative_percent",
      impact1Value: 0.01,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 10,
      active: true,
      comment: "Служебная задача, если хотите учитывать как отдельный uplift.",
    },
    17,
  ),
  createTask(
    {
      stream: "Recs and perso",
      taskName: "Gravity Field",
      stage1: "atc",
      impact1Type: "relative_percent",
      impact1Value: 0.015,
      stage2: undefined,
      impact2Type: undefined,
      impact2Value: 0,
      releaseMonth: 11,
      active: true,
      comment: "Персонализация, предзаполнена как uplift ATC CR.",
    },
    18,
  ),
  createTask(
    {
      stream: "Tech debt",
      taskName: "Load speed",
      stage1: "pdp",
      impact1Type: "relative_percent",
      impact1Value: 0.02,
      stage2: "atc",
      impact2Type: "relative_percent",
      impact2Value: 0.01,
      releaseMonth: 12,
      active: true,
      comment: "Load speed обычно улучшает глубину и последующие CR.",
    },
    19,
  ),
];
