create table if not exists public.roadmap_state (
  id bigint primary key generated by default as identity,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
