import pg from "pg";

const { Pool } = pg;

export class DatabaseNotConfiguredError extends Error {
  constructor() {
    super("PostgreSQL is not configured. Set DATABASE_URL or PGHOST/PGDATABASE/PGUSER.");
    this.name = "DatabaseNotConfiguredError";
  }
}

const hasDatabaseConfig = Boolean(
  process.env.DATABASE_URL ||
    (process.env.PGHOST && process.env.PGDATABASE && process.env.PGUSER),
);

const sslMode = (process.env.DATABASE_SSL || "").trim().toLowerCase();
const useSsl = ["1", "true", "require", "required"].includes(sslMode);

let pool;
let schemaPromise;

function getPool() {
  if (!hasDatabaseConfig) throw new DatabaseNotConfiguredError();
  if (pool) return pool;

  pool = new Pool({
    ...(process.env.DATABASE_URL ? { connectionString: process.env.DATABASE_URL } : {}),
    ...(useSsl ? { ssl: { rejectUnauthorized: false } } : {}),
    connectionTimeoutMillis: 10_000,
    idleTimeoutMillis: 30_000,
    max: Number(process.env.PGPOOL_MAX || 5),
  });

  pool.on("error", (error) => {
    console.error("[postgres] idle client error", error);
  });

  return pool;
}

async function ensureSchema() {
  if (!schemaPromise) {
    schemaPromise = getPool()
      .query(`
        create table if not exists public.roadmap_state (
          id bigint primary key generated by default as identity,
          payload jsonb not null default '{}'::jsonb,
          updated_at timestamptz not null default now()
        )
      `)
      .then(() => undefined)
      .catch((error) => {
        schemaPromise = undefined;
        throw error;
      });
  }
  return schemaPromise;
}

function toSerializableRow(row) {
  if (!row) return null;
  return {
    id: Number(row.id),
    payload: row.payload,
    updated_at:
      row.updated_at instanceof Date ? row.updated_at.toISOString() : row.updated_at ?? null,
  };
}

export async function getRoadmapState() {
  await ensureSchema();
  const result = await getPool().query(`
    select id, payload, updated_at
    from public.roadmap_state
    order by (id = 1) desc, updated_at desc
    limit 1
  `);
  return toSerializableRow(result.rows[0]);
}

export async function saveRoadmapState(payload) {
  await ensureSchema();
  const result = await getPool().query(
    `
      insert into public.roadmap_state (id, payload, updated_at)
      values (1, $1::jsonb, now())
      on conflict (id) do update
        set payload = excluded.payload,
            updated_at = excluded.updated_at
      returning id, payload, updated_at
    `,
    [JSON.stringify(payload)],
  );
  return toSerializableRow(result.rows[0]);
}

function mergeIdeas(existingPayload, ideas, fallbackPayload) {
  if (!existingPayload || typeof existingPayload !== "object" || Array.isArray(existingPayload)) {
    return { ...fallbackPayload, sharedIdeas: ideas, _writeMode: "ideas" };
  }

  if (existingPayload.yearPlans && typeof existingPayload.yearPlans === "object") {
    return { ...existingPayload, sharedIdeas: ideas, _writeMode: "ideas" };
  }

  // Compatibility with payloads created before multi-year plans were introduced.
  return { ...existingPayload, ideas, _writeMode: "ideas" };
}

export async function saveRoadmapIdeas(ideas, fallbackPayload) {
  await ensureSchema();
  const client = await getPool().connect();

  try {
    await client.query("begin");
    const selected = await client.query(`
      select id, payload
      from public.roadmap_state
      order by (id = 1) desc, updated_at desc
      limit 1
      for update
    `);
    const current = selected.rows[0];
    const nextPayload = mergeIdeas(current?.payload, ideas, fallbackPayload);

    const result = current
      ? await client.query(
          `
            update public.roadmap_state
            set payload = $1::jsonb, updated_at = now()
            where id = $2
            returning id, payload, updated_at
          `,
          [JSON.stringify(nextPayload), current.id],
        )
      : await client.query(
          `
            insert into public.roadmap_state (id, payload, updated_at)
            values (1, $1::jsonb, now())
            returning id, payload, updated_at
          `,
          [JSON.stringify(nextPayload)],
        );

    await client.query("commit");
    return toSerializableRow(result.rows[0]);
  } catch (error) {
    await client.query("rollback");
    throw error;
  } finally {
    client.release();
  }
}

export function isDatabaseConfigured() {
  return hasDatabaseConfig;
}
